baseURL = "https://us.shoogle.net/oregon"
languageCode = "en-US"
title = "Oregon"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "oregon"

[taxonomies]
  shop = "shops"

